=== TodaiRobotProject/classB/Center/Center-xml-dtd/torobo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD renewed on Jul 30, 2014. 7/22からの変更内容：(1)noteの子要素にsourceを追加。 6/30からの変更内容：(1)rbの子要素にunkを追加。(2)noteの子要素にquoteを追加。(3)captionの子要素にsubとsupを追加。  6/26からの変更内容：(1)cellの子要素にsupおよびsubを追加。(2)noteの子要素にformulaを追加。(3)infoの子要素にformulaを追加。(4)formulaの子要素にuTextを追加。(5)lineStart, paragraph要素を追加。(6)dataの子要素に、lineStart, paragraphを追加。 2014/3/13からの変更内容：(1)pageStartのpn属性をCDATAからIDに変更 (2)pageEndのpn属性をIMPLIEDに変更　3/13からの変更内容：(1)source, noteの子要素にrefを追加 12/20からの変更内容：(1)cellの子要素にimgを追加。(2)examの子要素に、pageStart, pageEndを追加。(3)lTextの子要素に、lTextを追加。(4)supおよびsubの子要素にrefを追加。  9/19からの変更内容：(1)ruby, rb, rtを追加。(2)unkタグを追加。(3)pageStart, pageEndを追加。  9/3からの変更内容：(1)ansColumnの下にblankがこれるようにした。(2)mathが、caption, data, questionの子になれるようにした。 8/21からの変更内容：(1)<okuriL><okuri><sub><sup><kaeri>がchoice, instruction, data, uText, lText, noteの子になれるようにした。(2)<sub><sup><ref>がformulaの子になれるようにした。(3)dataの子にcaptionが二つ入っているのを一つにした。(4)blankがsup, subの子になれるようにした。 8/20からの変更内容：(1) adataの子として、formula, mathを追加。8/19からの変更内容：<okuriL><okuri><sub><sup><kaeri>を追加した。 5/24からの変更内容：(1)imgにcorresponding_obj属性を追加。(2)adata要素を追加。属性として、id、type、fieldを定義。(3)adataが、data, choices, choice, question, instructionの各要素の子になれるようにした。 5/13日からの変更内容：(1)formulaの子にblankを追加 (2)choiceにansnum属性を追加 (3)cellの子にlTextを追加 (4) question, choicesのanscol属性をCDATAに-->

<!ELEMENT paragraph (#PCDATA |garbled| blank | img | lText | tbl | label | uText | caption | ansColumn | source | note | quote | choice|cNum|missing|ref |data|br|choices|formula|row|cell|adata|okuriL|okuri|sub|sup|kaeri|math|pageStart|pageEnd|unk|ruby|lineStart)*>
<!ATTLIST paragraph
	prn ID #REQUIRED
>

<!ELEMENT lineStart EMPTY>
<!ATTLIST lineStart
	ln ID #REQUIRED
>

<!ELEMENT pageStart EMPTY>
<!ATTLIST pageStart
	pn ID #REQUIRED
>
<!ELEMENT pageEnd EMPTY>
<!ATTLIST pageEnd
	pn CDATA #IMPLIED
>

<!ELEMENT unk (#PCDATA)*>
<!ATTLIST unk
	imgsrc CDATA #IMPLIED
	comment CDATA #IMPLIED
>

<!ELEMENT ruby (#PCDATA|rb|rt)*>
<!ELEMENT rb (#PCDATA|kaeri|unk)*>
<!ELEMENT rt (#PCDATA)*>

<!ELEMENT okuriL (#PCDATA)*>
<!ELEMENT sup (#PCDATA|blank|ref)*>
<!ELEMENT sub (#PCDATA|blank|ref)*>
<!ELEMENT kaeri (#PCDATA)*>
<!ELEMENT okuri (#PCDATA)*>

<!ELEMENT adata (#PCDATA|choices|choice|tbl|formula|math)*>
<!ATTLIST adata
	id ID #REQUIRED
	type CDATA #IMPLIED
	field CDATA #IMPLIED
>
<!ELEMENT caption (#PCDATA | label|garbled|ref|missing|blank|br|choice|cNum|lText|formula|quote|source|uText|math|pageStart|pageEnd|unk|ruby|sub|sup)*>
<!ELEMENT uText (#PCDATA | label|garbled|ref|missing|blank|br|choice|cNum|lText|formula|quote|source|uText|math|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST uText
	id ID #REQUIRED
>
<!ELEMENT title (#PCDATA|garbled |missing|br)*>
<!ELEMENT tbl (#PCDATA|row|label|choice|cNum|br|cell|blank|ref|uText|choices|formula|quote|source|garbled|missing|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST tbl
	numOfCols CDATA #IMPLIED
	numOfRows CDATA #IMPLIED
>
<!ELEMENT row (#PCDATA | cell|label|choice|br|blank|ref|cNum|uText|choices|formula|quote|source|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT ref (#PCDATA|garbled |missing|br|formula|uText|lText|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST ref
	comment CDATA #IMPLIED
	target IDREF #IMPLIED
>
<!ELEMENT question (#PCDATA |garbled| label | instruction | data | question | ansColumn | choice | img | tbl | choices|cNum|missing |ref|br|formula|quote|source|lText|info|adata|math|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST question
	id ID #REQUIRED
	minimal (null|yes | no) #REQUIRED
	answer_style CDATA #IMPLIED
	answer_type CDATA #IMPLIED
	knowledge_type CDATA #IMPLIED
	anscol CDATA #IMPLIED
	title CDATA #IMPLIED
	sectionId CDATA #IMPLIED
	comment CDATA #IMPLIED
>
<!ELEMENT label (#PCDATA|br|garbled|missing)*>
<!ELEMENT lText (#PCDATA |garbled| label|ref|missing|blank|br|choice|cNum|uText|formula|quote|source|math|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby|lText)*>
<!ATTLIST lText
	id ID #REQUIRED
>
<!ELEMENT instruction (#PCDATA |garbled| ref|missing |label |ansColumn|lText|uText|br|blank|formula|quote|source|img|choices|data|math|adata|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT info (#PCDATA|garbled|missing|br|formula)*>
<!ELEMENT img EMPTY>
<!ATTLIST img
	src CDATA #REQUIRED
	comment CDATA #IMPLIED
	corresponding_obj IDREFS #IMPLIED
>
<!ELEMENT exam (#PCDATA|title|info|question|cNum|label|garbled|missing|choice|choices|br|ref|ansColumn|pageStart|pageEnd)*>
<!ATTLIST exam
	source CDATA #IMPLIED
	srcTxtURL CDATA #IMPLIED
	subject CDATA #REQUIRED
	year CDATA #IMPLIED
	range_of_options IDREFS #IMPLIED
	num_of_options CDATA #IMPLIED
	xml:space (default|preserve) "default"
>
<!ELEMENT data (#PCDATA |garbled| blank | img | lText | tbl | label | uText | caption | ansColumn | source | note | quote | choice|cNum|missing|ref |data|br|choices|formula|row|cell|adata|okuriL|okuri|sub|sup|kaeri|math|pageStart|pageEnd|unk|ruby|lineStart|paragraph)*>
<!ATTLIST data
	id ID #REQUIRED
	type (complex | text | table | image ) #REQUIRED
>
<!ELEMENT choices (#PCDATA |garbled| cNum | ref | img | tbl | row | cell| uText | lText |choice|missing|br |label|formula|quote|source|adata|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST choices
	comment CDATA #IMPLIED
	anscol CDATA #IMPLIED
>
<!ELEMENT choice (#PCDATA |garbled| cNum | ref | img | tbl | uText | lText|missing |cell|br|label|formula|quote|source|math|data|adata|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST choice
	ra (no | yes) #IMPLIED
	comment CDATA #IMPLIED
	ansnum CDATA #IMPLIED
>
<!ELEMENT cell (#PCDATA |garbled| blank | ansColumn | ref|missing|label|cNum|br |choice|uText|choices|formula|quote|source|lText|math|pageStart|pageEnd|unk|ruby|img|sub|sup)*>
<!ATTLIST cell
	type (label | data) #IMPLIED
	colspan CDATA #IMPLIED
	rowspan CDATA #IMPLIED
>

<!ELEMENT cNum (#PCDATA|garbled|missing|br)*>
<!ELEMENT blank (#PCDATA |garbled| label | ansColumn|missing|br)*>
<!ATTLIST blank
	id ID #REQUIRED
	digits CDATA #IMPLIED
>
<!ELEMENT ansColumn (#PCDATA | label|garbled|missing|ref|br|blank)*>
<!ATTLIST ansColumn
	id ID #REQUIRED
>
<!ELEMENT source (#PCDATA|garbled|missing|br|pageStart|pageEnd|unk|ruby|ref)*>
<!ELEMENT note (#PCDATA | label|garbled|missing|br|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby|ref|formula|quote|source)*>
<!ATTLIST note id ID #REQUIRED>
<!ELEMENT quote (#PCDATA|garbled|missing|br|uText|lText|ref|label|blank|note|source|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT garbled (#PCDATA|br|label)*>
<!ATTLIST garbled correction CDATA #IMPLIED>
<!ELEMENT missing EMPTY>
<!ATTLIST missing string CDATA #IMPLIED>
<!ELEMENT formula (#PCDATA|garbled|missing|br|blank|ref|sub|sup|uText)*>
<!ATTLIST formula comment CDATA #IMPLIED>
<!ELEMENT br EMPTY>

=== TodaiRobotProject/classB/sample_problems/sample-SekaishiB.xml
<?xml version='1.0'?>
<!DOCTYPE exam PUBLIC "-//TOROBO//TOROBO ANNOTATION 1.0//EN" "torobo.dtd">
<?xml-stylesheet type="text/css" href="../torobo.css"?>

<exam source="National Center For University Entrance Examination" subject="SekaishiB(main exam)" year="2009">
  Center-2009--Main-SekaishiB<br/>
  <title>
    2009年度 本試験 世界史Ｂ<br/><br/>
  </title>
  <question id="Q1" minimal="no">
    <label>【１】</label>
    <instruction>
      <br/><br/> 人類が営む生業と労働は，経済・社会・政治の動きと密接にかかわりながら，大きく変容してきた。生業と労働の歴史について述べた次の文章Ａ～Ｃを読み，以下の問い(問１～９)に答えよ。<br/> (配点 25)<br/>
    </instruction>
    <data id="D0" type="text">
      <label>Ａ</label><br/> 清の学者趙翼は，明代の文化人の趨勢を論じて，<uText id="U1"><label>(1)</label>唐宋以来，文化・芸術に秀でた者の多くは科挙の合格者であった</uText>が，<uText id="U2"><label>(2)</label>明代</uText>になってその担い手は在野の人物に移っていったと述べている。明代中期の画家唐寅は，まさにその過渡期の人物と言える。彼は科挙で優秀な成績を収めながらも，不運な事件に巻き込まれ，栄達の道を絶たれてからは，蘇州で画業をなりわいとしながら自由奔放な生活を送った。明代中期から後期にかけて，在野の芸術家や文筆家が続々と現れたのは，<uText id="U3"><label>(3)</label>江南を中心とする商工業の発展</uText>によって都市の文化が成熟し，絵画や出版物が広く商品としての価値を持つようになったからであった。<br/><br/>
    </data>
    <question anscol="A1" answer_style="multipleChoice" answer_type="sentence" id="Q2" knowledge_type="KS" minimal="yes">
      <label>問１</label>
      <instruction>
         下線部<ref comment="" target="U1">(1)</ref>に関連して，次に挙げる人物は，いずれも唐代から宋代にかけての科挙の合格者である。それぞれの人物について述べた文として正しいものを，次の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A1">１</ansColumn><br/>
      <choices anscol="A1" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 欧陽脩や蘇軾は，唐代を代表する文筆家である。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 顔真卿は，宋代を代表する書家である。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 宋の王安石は，新法と呼ばれる改革を行った。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 秦檜は，元との関係をめぐり主戦派と対立した。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A2" answer_style="multipleChoice" answer_type="sentence" id="Q3" knowledge_type="KS" minimal="yes">
      <label>問２</label>
      <instruction>
         下線部<ref comment="" target="U2">(2)</ref>の時代に起こった出来事について述べた文として最も適当なものを，次の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A2">２</ansColumn><br/>
      <choices anscol="A2" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 中国で日本銀が流通した。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 禅宗と呼ばれる仏教の一派が生まれた。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 戯曲『西廂記』が生まれた。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 臨安(現在の杭州)に都が置かれた。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A3" answer_style="multipleChoice" answer_type="(symbol-term_other)*2" id="Q4" knowledge_type="KS" minimal="yes">
      <label>問３</label>
      <instruction>
         下線部<ref comment="" target="U3">(3)</ref>について述べた次の文章中の <ref target="B1">ア</ref> と<ref target="B2"> イ</ref> に入れる語の組合せとして正しいものを，以下の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A3">３</ansColumn><br/><br/>
      <data id="D12" type="text">
        明代中期から，長江下流域では絹織物や綿織物などの手工業が発展する一方，穀倉地帯は長江中流域に広がり，「<blank id="B1"><label>ア</label></blank> 熟すれば天下足る」という言葉が生まれた。山西商人や新安商人が活躍し，各地の都市に互助組織である会館や<blank id="B2"><label>イ</label></blank> が置かれた。<br/>
      </data>
      <br/>
      <choices anscol="A3" comment="">
        <choice ansnum="1">
          <cNum>①</cNum><ref comment="" target="B1">ア</ref>−湖 広 <ref comment="" target="B2">イ</ref>−公 所 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum><ref comment="" target="B1">ア</ref>−湖 広 <ref comment="" target="B2">イ</ref>−租 界 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum><ref comment="" target="B1">ア</ref>−蘇湖(江浙) <ref comment="" target="B2">イ</ref>−公 所 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum><ref comment="" target="B1">ア</ref>−蘇湖(江浙) <ref comment="" target="B2">イ</ref>−租 界 
        </choice>
        <br/>
      </choices>
    </question>
    <data id="D1" type="text">
      <label>Ｂ</label><br/> アルプス以北のヨーロッパでは，<uText id="U4"><label>(4)</label>農民や都市の下層民</uText>が，一つの生業で生活を維持するのが困難であることも珍しくなかった。とりわけ，<uText id="U5"><label>(5)</label>15世紀後半から16世紀後半</uText>には，人口増加の影響もあって，大量の貧農や困窮した下層民が生み出され，<uText id="U6"><label>(6)</label>彼らの中には，傭兵の道を選ぶ者も少なくなかった。</uText>徴募時の一時金や給与は，彼らの生活を支えた。三十年戦争は，こうした傭兵たちを主な担い手とした戦争だったのである。<br/><br/>
    </data>
    <question anscol="A4" answer_style="multipleChoice" answer_type="sentence" id="Q5" knowledge_type="KS" minimal="yes">
      <label>問４</label>
      <instruction>
         下線部<ref comment="" target="U4">(4)</ref>に関連して，農村や都市について述べた文として最も適当なものを，次の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A4">４</ansColumn><br/>
      <choices anscol="A4" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 11世紀に，イギリスでは，牧羊を目的に囲い込みが行われた。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 12世紀に，エルベ川以東に，農場領主制(グーツヘルシャフト)が広まった。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> ギルドは，生産・流通の自由競争を保障するために組織された。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> ハンザ同盟は，リューベックを盟主とした。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A5" answer_style="multipleChoice" answer_type="sentence" id="Q6" knowledge_type="KS" minimal="yes">
      <label>問５</label>
      <instruction>
         下線部<ref comment="" target="U5">(5)</ref>の時期に起こった出来事について述べた文として正しいものを，次の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A5">５</ansColumn><br/>
      <choices anscol="A5" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> ドイツでは，シュマルカルデン同盟が結成された。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> インドでは，マラータ同盟が結成された。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> イギリスでは，ワット＝タイラーの乱が起こった。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 中国では，紅巾の乱が起こった。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A6" answer_style="multipleChoice" answer_type="sentence" id="Q7" knowledge_type="KS" minimal="yes">
      <label>問６</label>
      <instruction>
         下線部<ref comment="" target="U6">(6)</ref>に関連して，兵制や兵士について述べた文として最も適当なものを，次の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A6">６</ansColumn><br/>
      <choices anscol="A6" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> ポエニ戦争後，重装歩兵として従軍した農民層は経済的に豊かになった。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 八旗は，順治帝が創設した軍隊である。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> イェニチェリは，オスマン帝国の常備軍であった。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> フランク王国では，テマ制(軍管区制)の下で屯田兵制が行われた。 
        </choice>
        <br/>
      </choices>
    </question>
    <data id="D2" type="text">
      <label>Ｃ</label><br/> 「鉄鋼王」と呼ばれたアンドルー＝カーネギーは，近代における生業と労働の変容とともに人生を歩んだ人物である。彼は，1848年，家族に連れられ，スコットランドからアメリカ合衆国に移住した。その背景は，<uText id="U7"><label>(7)</label>工場製の安価な綿織物の普及</uText>により，家業の毛織物業が苦境に陥ったことにあった。鉄道の電信技師として働いた後，彼は実業家へと転じ，新技術を活用した鉄鋼業で成功を収めた。この時期の<uText id="U8"><label>(8)</label>大規模な産業構造の転換</uText>は，職人や農民から工場労働者へと転じる人々の急増，ホワイトカラーの出現など，生業と労働のあり方を大きく変容させた。また，<uText id="U9"><label>(9)</label>労働問題</uText>の深刻化もその帰結の一つであった。カーネギーの製鉄会社でも，生産の拡大とともに労働争議が頻発したのである。<br/><br/>
    </data>
    <question anscol="A7" answer_style="multipleChoice" answer_type="sentence" id="Q8" knowledge_type="KS" minimal="yes">
      <label>問７</label>
      <instruction>
         下線部<ref comment="" target="U7">(7)</ref>に関連して，イギリスの商業・製造業にかかわる出来事について述べた文として正しいものを，次の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A7">７</ansColumn><br/>
      <choices anscol="A7" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> イギリスは，マカートニーを派遣して清に自由貿易を認めさせた。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> イギリスでは，機械を打ち壊すラダイト運動が起こった。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 茶法の廃止をきっかけに，イギリスの北米植民地で，ボストン茶会事件が起こった。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> ナポレオンは，イギリスとアメリカ合衆国の間の通商を断絶させるために，大陸封鎖令を出した。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A8" answer_style="multipleChoice" answer_type="sentence" id="Q9" knowledge_type="KS" minimal="yes">
      <label>問８</label>
      <instruction>
         下線部<ref comment="" target="U8">(8)</ref>に関連して，アメリカ合衆国の産業・経済について述べた文として最も適当なものを，次の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A8">８</ansColumn><br/>
      <choices anscol="A8" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 19世紀後半，エディソンがダイナマイトを発明した。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> フォードは，自動車の大量生産方式を生み出した。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 19世紀前半，映画産業が繁栄した。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 農業調整法(AAA)によって，農産物価格の引き下げが行われた。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A9" answer_style="multipleChoice" answer_type="sentence" id="Q10" knowledge_type="KS" minimal="yes">
      <label>問９</label>
      <instruction>
         下線部<ref comment="" target="U9">(9)</ref>に対する各国ないし国際機関の取り組みについて述べた文として誤っているものを，次の①～④のうちから一つ選べ。 
      </instruction>
      <ansColumn id="A9">９</ansColumn><br/>
      <choices anscol="A9" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> フランスの二月革命で成立した臨時政府は，国立作業場を設置した。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 国際連盟に，国際労働機関(ILO)が付置された。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> アメリカ合衆国では，ワグナー法によって労働者の団結権が確定した。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> イギリスでは，マクドナルド内閣の下，労働組合が合法化された。 
        </choice>
        <br/>
      </choices>
    </question>
  </question>
</exam>

=== TodaiRobotProject/classB/sample_problems/sample-KagakuI.xml
<?xml version='1.0'?>
<!DOCTYPE exam PUBLIC "-//TOROBO//TOROBO ANNOTATION 1.0//EN" "torobo.dtd">
<?xml-stylesheet type="text/css" href="../torobo.css"?>

<exam source="National Center For University Entrance Examination" subject="KagakuI(main exam)" year="2009">
  Center-2009--Main-KagakuI<br/>
  <title>
    2009年度 本試験 化学Ⅰ<br/><br/>
  </title>
   必要があれば，原子量は次の値を使うこと。<br/> H 1.0 C 12 N 14 O 16 Na 23 S 32 Cu また，問題文中の体積の単位記号Ｌは，リットルを表す。<br/><br/>
  <question id="Q1" minimal="no">
    <label>【１】</label>
    <instruction>
      <br/><br/> 次の問い(問１～６)に答えよ。<br/>
    </instruction>
    (配点 25)<br/>
    <question id="Q2" minimal="no">
      <label>問１</label>
      <instruction>
         次の<ref target="L1">ａ</ref>・<ref comment="" target="L2">ｂ</ref>に当てはまるものを，それぞれの解答群の①～⑤のうちから一つずつ選べ。<br/>
      </instruction>
      <question anscol="A11" answer_style="multipleChoice" answer_type="term_other" id="Q36" knowledge_type="KS,DM_C1" minimal="yes">
        <data id="D7" type="text">
          <br/><lText id="L1"><label>ａ</label> 分子からなる物質</lText>
        </data>
        <ansColumn id="A11">１</ansColumn><br/>
        <choices anscol="A11" comment="">
          <choice ansnum="1">
            <cNum>①</cNum> 亜 鉛 
          </choice>
          <choice ansnum="2">
            <cNum>②</cNum> 塩化水素 
          </choice>
          <choice ansnum="3">
            <cNum>③</cNum> 塩化ナトリウム 
          </choice>
          <choice ansnum="4">
            <cNum>④</cNum> 炭酸水素ナトリウム 
          </choice>
          <choice ansnum="5">
            <cNum>⑤</cNum> ミョウバン 
          </choice>
          <br/>
        </choices>
      </question>
      <question anscol="A12" answer_style="multipleChoice" answer_type="term_other" id="Q37" knowledge_type="KS,DM_C1" minimal="yes">
        <data id="D6" type="text">
          <lText id="L2"><label>ｂ</label> 二重結合をもたない分子</lText>
        </data>
        <ansColumn id="A12">２</ansColumn><br/>
        <choices anscol="A12" comment="">
          <choice ansnum="1">
            <cNum>①</cNum> 二酸化炭素 
          </choice>
          <choice ansnum="2">
            <cNum>②</cNum> 酢 酸 
          </choice>
          <choice ansnum="3">
            <cNum>③</cNum> アセトアルデヒド 
          </choice>
          <choice ansnum="4">
            <cNum>④</cNum> エタノール 
          </choice>
          <choice ansnum="5">
            <cNum>⑤</cNum> プロペン(プロピレン) 
          </choice>
          <br/>
        </choices>
      </question>
    </question>
    <question anscol="A13" answer_style="multipleChoice" answer_type="sentence" id="Q3" knowledge_type="KS,DM_C1" minimal="yes">
      <label>問２</label>
      <instruction>
         二つの原子が互いに同位体であることを示す記述として正しいものを，次の①～⑤のうちから一つ選べ。
      </instruction>
      <ansColumn id="A13">３</ansColumn><br/>
      <choices anscol="A13" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 陽子の数は等しいが，質量数が異なる。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 陽子の数は異なるが，質量数が等しい。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 陽子の数と中性子の数の和が等しい。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 中性子の数は異なるが，質量数が等しい。 
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> 中性子の数は等しいが，質量数が異なる。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A14" answer_style="multipleChoice" answer_type="sentence" id="Q4" knowledge_type="KS,DM_C1" minimal="yes">
      <label>問３</label>
      <instruction>
         イオンに関する記述として誤りを含むものを，次の①～⑤のうちから一つ選べ。
      </instruction>
      <ansColumn id="A14">４</ansColumn><br/>
      <choices anscol="A14" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> イオン化エネルギー(第一イオン化エネルギー)は，原子から電子を１個取り去って陽イオンにするのに必要な最小のエネルギーである。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> イオン結晶に含まれる陽イオンの数と陰イオンの数は，必ず等しい。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 塩素原子は，電子を受け取って１価の陰イオンになりやすい。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> ナトリウムイオンは，ネオン原子と同じ電子配置をもつ。 
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> イオン結合は，陽イオンと陰イオンの静電気的な引力による結合である。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A15" answer_style="multipleChoice" answer_type="sentence" id="Q5" knowledge_type="KS,DM_C1" minimal="yes">
      <label>問４</label>
      <instruction>
         標準状態における体積が最も大きいものを，次の①～⑤のうちから一つ選べ。
      </instruction>
      <ansColumn id="A15">５</ansColumn><br/>
      <choices anscol="A15" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 2.0gの<formula>H2</formula>
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 標準状態で20ＬのHe 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 88gの<formula>CO2</formula>
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 28gの<formula>N2</formula>と標準状態で5.6Ｌの<formula>O2</formula>との混合気体 
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> 2.5molの<formula>CH4</formula>
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A16" answer_style="multipleChoice" answer_type="formula" id="Q6" knowledge_type="KS,DM_C1" minimal="yes">
      <label>問５</label>
      <instruction>
         質量パーセント濃度8.0％の水酸化ナトリウム水溶液の密度は1.1<formula>g/cm3</formula>である。この溶液100<formula>cm3</formula>に含まれる水酸化ナトリウムの物質量は何molか。最も適当な数値を，次の①～⑥のうちから一つ選べ。
      </instruction>
      <ansColumn id="A16">６</ansColumn> mol<br/>
      <choices anscol="A16" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 0.18 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 0.20 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 0.22 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 0.32 
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> 0.35 
        </choice>
        <choice ansnum="6">
          <cNum>⑥</cNum> 0.38 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A17" answer_style="multipleChoice" answer_type="sentence" id="Q7" knowledge_type="KS,DM_C3" minimal="yes">
      <label>問６</label>
      <instruction>
         身の回りの現象や物質・製品に関する記述として下線部に誤りを含むものを，次の①～⑤のうちから一つ選べ。
      </instruction>
      <ansColumn id="A17">７</ansColumn><br/>
      <choices anscol="A17" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 鉄粉を用いている使い捨てカイロは，空気中で発熱する。これは，<uText id="U6">鉄が酸化されるため</uText>である。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 火山地帯や温泉では，卵の腐ったようなにおい(腐卵臭)がすることがある。<uText id="U7">これは硫化水素のにおいである</uText>。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 炭酸飲料をコップに入れて室温に放置すると，しだいに発泡しなくなる。これは，<uText id="U8">飲料中に溶解している二酸化炭素の量が減少するため</uText>である。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> セッケンの洗浄力は硬水中では低下する。これは，<uText id="U9">セッケンがNa＋と反応して水に溶けにくい塩をつくるため</uText>である。 
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> 希ガスは電球の封入ガスに使われる。これは，<uText id="U10">希ガスが他の物質と反応しにくいため</uText>である。 
        </choice>
        <br/>
      </choices>
    </question>
  </question>
</exam>

=== TodaiRobotProject/classB/sample_problems/sample-ButsuriI.xml
<?xml version='1.0'?>
<!DOCTYPE exam PUBLIC "-//TOROBO//TOROBO ANNOTATION 1.0//EN" "torobo.dtd">
<?xml-stylesheet type="text/css" href="../torobo.css"?>
<exam source="National Center For University Entrance Examination" subject="ButsuriI(main exam)" year="2009">
  Center-2009--Main-ButsuriI<br/>
  <title>
    2009年度 本試験 物理Ⅰ<br/>
    <br/>
  </title>
  <question id="Q1" minimal="no">
    <label>【１】</label>
    <instruction>
      <br/>
      <br/>
       次の問い(問１～６)に答えよ。<br/>
    </instruction>
    (配点 30)<br/>
    <question anscol="A11,A12" answer_style="multipleChoice" answer_type="formula" id="Q2" knowledge_type="KS,DM_P3" minimal="yes">
      <label>問１</label>
      <instruction>
         次の文章中の空欄<ref target="B1"><missing string="1"/></ref>・<ref target="B2"><missing string="2"/></ref>に入れる数値として正しいものを，以下の①～⑤のうちから一つずつ選べ。ただし，同じものを繰り返し選んでもよい。<br/>
      </instruction>
      <ansColumn id="A11"><missing string="1"/></ansColumn><ansColumn id="A12"><missing string="2"/></ansColumn><br/>
      <data id="D7" type="text">
        水平なあらい面上で物体をすべらせ，すべり始めてから停止するまでの距離が初速度または動摩擦係数によってどのように変わるかを考える。動摩擦係数が同じ場合，初速度が2倍になると，停止するまでの距離は<blank id="B1"><missing string="1"/></blank>倍になる。一方，初速度が同じ場合，動摩擦係数が<formula/>倍になると，停止するまでの距離は<blank id="B2"><missing string="2"/></blank>倍になる。<br/>
      </data>
      <br/>
      <choices anscol="A11 A12" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 1 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum><formula/><formula comment="mℊsinθ"/>
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 2 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum><formula/>
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> 4 
        </choice>
        <br/>
      </choices>
    </question>
  </question>
</exam>
