=== TodaiRobotProject/classB/Center/Center-xml-dtd/torobo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD renewed on Jul 30, 2014. 7/22からの変更内容：(1)noteの子要素にsourceを追加。 6/30からの変更内容：(1)rbの子要素にunkを追加。(2)noteの子要素にquoteを追加。(3)captionの子要素にsubとsupを追加。  6/26からの変更内容：(1)cellの子要素にsupおよびsubを追加。(2)noteの子要素にformulaを追加。(3)infoの子要素にformulaを追加。(4)formulaの子要素にuTextを追加。(5)lineStart, paragraph要素を追加。(6)dataの子要素に、lineStart, paragraphを追加。 2014/3/13からの変更内容：(1)pageStartのpn属性をCDATAからIDに変更 (2)pageEndのpn属性をIMPLIEDに変更　3/13からの変更内容：(1)source, noteの子要素にrefを追加 12/20からの変更内容：(1)cellの子要素にimgを追加。(2)examの子要素に、pageStart, pageEndを追加。(3)lTextの子要素に、lTextを追加。(4)supおよびsubの子要素にrefを追加。  9/19からの変更内容：(1)ruby, rb, rtを追加。(2)unkタグを追加。(3)pageStart, pageEndを追加。  9/3からの変更内容：(1)ansColumnの下にblankがこれるようにした。(2)mathが、caption, data, questionの子になれるようにした。 8/21からの変更内容：(1)<okuriL><okuri><sub><sup><kaeri>がchoice, instruction, data, uText, lText, noteの子になれるようにした。(2)<sub><sup><ref>がformulaの子になれるようにした。(3)dataの子にcaptionが二つ入っているのを一つにした。(4)blankがsup, subの子になれるようにした。 8/20からの変更内容：(1) adataの子として、formula, mathを追加。8/19からの変更内容：<okuriL><okuri><sub><sup><kaeri>を追加した。 5/24からの変更内容：(1)imgにcorresponding_obj属性を追加。(2)adata要素を追加。属性として、id、type、fieldを定義。(3)adataが、data, choices, choice, question, instructionの各要素の子になれるようにした。 5/13日からの変更内容：(1)formulaの子にblankを追加 (2)choiceにansnum属性を追加 (3)cellの子にlTextを追加 (4) question, choicesのanscol属性をCDATAに-->

<!ELEMENT paragraph (#PCDATA |garbled| blank | img | lText | tbl | label | uText | caption | ansColumn | source | note | quote | choice|cNum|missing|ref |data|br|choices|formula|row|cell|adata|okuriL|okuri|sub|sup|kaeri|math|pageStart|pageEnd|unk|ruby|lineStart)*>
<!ATTLIST paragraph
	prn ID #REQUIRED
>

<!ELEMENT lineStart EMPTY>
<!ATTLIST lineStart
	ln ID #REQUIRED
>

<!ELEMENT pageStart EMPTY>
<!ATTLIST pageStart
	pn ID #REQUIRED
>
<!ELEMENT pageEnd EMPTY>
<!ATTLIST pageEnd
	pn CDATA #IMPLIED
>

<!ELEMENT unk (#PCDATA)*>
<!ATTLIST unk
	imgsrc CDATA #IMPLIED
	comment CDATA #IMPLIED
>

<!ELEMENT ruby (#PCDATA|rb|rt)*>
<!ELEMENT rb (#PCDATA|kaeri|unk)*>
<!ELEMENT rt (#PCDATA)*>

<!ELEMENT okuriL (#PCDATA)*>
<!ELEMENT sup (#PCDATA|blank|ref)*>
<!ELEMENT sub (#PCDATA|blank|ref)*>
<!ELEMENT kaeri (#PCDATA)*>
<!ELEMENT okuri (#PCDATA)*>

<!ELEMENT adata (#PCDATA|choices|choice|tbl|formula|math)*>
<!ATTLIST adata
	id ID #REQUIRED
	type CDATA #IMPLIED
	field CDATA #IMPLIED
>
<!ELEMENT caption (#PCDATA | label|garbled|ref|missing|blank|br|choice|cNum|lText|formula|quote|source|uText|math|pageStart|pageEnd|unk|ruby|sub|sup)*>
<!ELEMENT uText (#PCDATA | label|garbled|ref|missing|blank|br|choice|cNum|lText|formula|quote|source|uText|math|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST uText
	id ID #REQUIRED
>
<!ELEMENT title (#PCDATA|garbled |missing|br)*>
<!ELEMENT tbl (#PCDATA|row|label|choice|cNum|br|cell|blank|ref|uText|choices|formula|quote|source|garbled|missing|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST tbl
	numOfCols CDATA #IMPLIED
	numOfRows CDATA #IMPLIED
>
<!ELEMENT row (#PCDATA | cell|label|choice|br|blank|ref|cNum|uText|choices|formula|quote|source|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT ref (#PCDATA|garbled |missing|br|formula|uText|lText|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST ref
	comment CDATA #IMPLIED
	target IDREF #IMPLIED
>
<!ELEMENT question (#PCDATA |garbled| label | instruction | data | question | ansColumn | choice | img | tbl | choices|cNum|missing |ref|br|formula|quote|source|lText|info|adata|math|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST question
	id ID #REQUIRED
	minimal (null|yes | no) #REQUIRED
	answer_style CDATA #IMPLIED
	answer_type CDATA #IMPLIED
	knowledge_type CDATA #IMPLIED
	anscol CDATA #IMPLIED
	title CDATA #IMPLIED
	sectionId CDATA #IMPLIED
	comment CDATA #IMPLIED
>
<!ELEMENT label (#PCDATA|br|garbled|missing)*>
<!ELEMENT lText (#PCDATA |garbled| label|ref|missing|blank|br|choice|cNum|uText|formula|quote|source|math|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby|lText)*>
<!ATTLIST lText
	id ID #REQUIRED
>
<!ELEMENT instruction (#PCDATA |garbled| ref|missing |label |ansColumn|lText|uText|br|blank|formula|quote|source|img|choices|data|math|adata|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT info (#PCDATA|garbled|missing|br|formula)*>
<!ELEMENT img EMPTY>
<!ATTLIST img
	src CDATA #REQUIRED
	comment CDATA #IMPLIED
	corresponding_obj IDREFS #IMPLIED
>
<!ELEMENT exam (#PCDATA|title|info|question|cNum|label|garbled|missing|choice|choices|br|ref|ansColumn|pageStart|pageEnd)*>
<!ATTLIST exam
	source CDATA #IMPLIED
	srcTxtURL CDATA #IMPLIED
	subject CDATA #REQUIRED
	year CDATA #IMPLIED
	range_of_options IDREFS #IMPLIED
	num_of_options CDATA #IMPLIED
	xml:space (default|preserve) "default"
>
<!ELEMENT data (#PCDATA |garbled| blank | img | lText | tbl | label | uText | caption | ansColumn | source | note | quote | choice|cNum|missing|ref |data|br|choices|formula|row|cell|adata|okuriL|okuri|sub|sup|kaeri|math|pageStart|pageEnd|unk|ruby|lineStart|paragraph)*>
<!ATTLIST data
	id ID #REQUIRED
	type (complex | text | table | image ) #REQUIRED
>
<!ELEMENT choices (#PCDATA |garbled| cNum | ref | img | tbl | row | cell| uText | lText |choice|missing|br |label|formula|quote|source|adata|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST choices
	comment CDATA #IMPLIED
	anscol CDATA #IMPLIED
>
<!ELEMENT choice (#PCDATA |garbled| cNum | ref | img | tbl | uText | lText|missing |cell|br|label|formula|quote|source|math|data|adata|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST choice
	ra (no | yes) #IMPLIED
	comment CDATA #IMPLIED
	ansnum CDATA #IMPLIED
>
<!ELEMENT cell (#PCDATA |garbled| blank | ansColumn | ref|missing|label|cNum|br |choice|uText|choices|formula|quote|source|lText|math|pageStart|pageEnd|unk|ruby|img|sub|sup)*>
<!ATTLIST cell
	type (label | data) #IMPLIED
	colspan CDATA #IMPLIED
	rowspan CDATA #IMPLIED
>

<!ELEMENT cNum (#PCDATA|garbled|missing|br)*>
<!ELEMENT blank (#PCDATA |garbled| label | ansColumn|missing|br)*>
<!ATTLIST blank
	id ID #REQUIRED
	digits CDATA #IMPLIED
>
<!ELEMENT ansColumn (#PCDATA | label|garbled|missing|ref|br|blank)*>
<!ATTLIST ansColumn
	id ID #REQUIRED
>
<!ELEMENT source (#PCDATA|garbled|missing|br|pageStart|pageEnd|unk|ruby|ref)*>
<!ELEMENT note (#PCDATA | label|garbled|missing|br|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby|ref|formula|quote|source)*>
<!ATTLIST note id ID #REQUIRED>
<!ELEMENT quote (#PCDATA|garbled|missing|br|uText|lText|ref|label|blank|note|source|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT garbled (#PCDATA|br|label)*>
<!ATTLIST garbled correction CDATA #IMPLIED>
<!ELEMENT missing EMPTY>
<!ATTLIST missing string CDATA #IMPLIED>
<!ELEMENT formula (#PCDATA|garbled|missing|br|blank|ref|sub|sup|uText)*>
<!ATTLIST formula comment CDATA #IMPLIED>
<!ELEMENT br EMPTY>

=== TodaiRobotProject/classB/sample_problems/sample-Eigo_hikki.xml
<?xml version='1.0'?>
<!DOCTYPE exam PUBLIC "-//TOROBO//TOROBO ANNOTATION 1.0//EN" "torobo.dtd">
<?xml-stylesheet type="text/css" href="../torobo.css"?>
<exam source="National Center For University Entrance Examination" subject="Eigo_hikki(main exam)" year="2009">
  ﻿Center-2009--Main-Eigo_hikki<br/>
  <title>
    2009年度 本試験 英語(筆記)<br/>
    <br/>
  </title>
  <question id="Q1" minimal="no">
    <label>【１】</label>
    <instruction>
      <br/>
      <br/>
       次の問い(Ａ～Ｄ)に答えよ。<br/>
    </instruction>
     (配点 16)<br/>
    <question id="Q2" minimal="no">
      <label>Ａ</label>
      <instruction>
         次の問い(問１～３)において，下線部の発音が，ほかの三つの場合と異なるものを，それぞれ以下の①～④のうちから一つずつ選べ。<br/>
      </instruction>
      <br/>
      <question anscol="A1" answer_style="multipleChoice" answer_type="orthography" id="Q3" knowledge_type="PRN" minimal="yes">
        <label>問１</label>
        <data id="D0" type="text">
          <ansColumn id="A1">1</ansColumn>
          <br/>
        </data>
        <choices anscol="A1" comment="">
          <choice ansnum="1">
            <cNum>①</cNum> abs<uText id="U1">or</uText>b 
          </choice>
          <choice ansnum="2">
            <cNum>②</cNum> comf<uText id="U2">or</uText>t 
          </choice>
          <choice ansnum="3">
            <cNum>③</cNum> f<uText id="U3">or</uText>mal 
          </choice>
          <choice ansnum="4">
            <cNum>④</cNum> newb<uText id="U4">or</uText>n 
          </choice>
          <br/>
        </choices>
      </question>
      <question anscol="A2" answer_style="multipleChoice" answer_type="orthography" id="Q4" knowledge_type="PRN" minimal="yes">
        <label>問２</label>
        <data id="D1" type="text">
          <ansColumn id="A2">2</ansColumn>
          <br/>
        </data>
        <choices anscol="A2" comment="">
          <choice ansnum="1">
            <cNum>①</cNum> de<uText id="U5">b</uText>t 
          </choice>
          <choice ansnum="2">
            <cNum>②</cNum> dou<uText id="U6">b</uText>t 
          </choice>
          <choice ansnum="3">
            <cNum>③</cNum> su<uText id="U7">b</uText>title 
          </choice>
          <choice ansnum="4">
            <cNum>④</cNum> su<uText id="U8">b</uText>tle 
          </choice>
          <br/>
        </choices>
      </question>
      <question anscol="A3" answer_style="multipleChoice" answer_type="orthography" id="Q5" knowledge_type="PRN" minimal="yes">
        <label>問３</label>
        <data id="D2" type="text">
          <ansColumn id="A3">3</ansColumn>
          <br/>
        </data>
        <choices anscol="A3" comment="">
          <choice ansnum="1">
            <cNum>①</cNum> ea<uText id="U9">g</uText>er 
          </choice>
          <choice ansnum="2">
            <cNum>②</cNum> fra<uText id="U10">g</uText>ile 
          </choice>
          <choice ansnum="3">
            <cNum>③</cNum> gin<uText id="U11">g</uText>er 
          </choice>
          <choice ansnum="4">
            <cNum>④</cNum> ur<uText id="U12">g</uText>ent 
          </choice>
          <br/>
        </choices>
      </question>
    </question>
    <question id="Q6" minimal="no">
      <label>Ｂ</label>
      <instruction>
         次の問い(問１・問２)において，与えられた語と第一アクセント(第一強勢)の位置が同じ語を，それぞれ以下の①～④のうちから一つずつ選べ。<br/>
      </instruction>
      <br/>
      <question anscol="A4" answer_style="multipleChoice" answer_type="orthography" id="Q7" knowledge_type="PRN" minimal="yes">
        <label>問１</label>
        <data id="D3" type="text">
           accustom <ansColumn id="A4">4</ansColumn>
          <br/>
        </data>
        <choices anscol="A4" comment="">
          <choice ansnum="1">
            <cNum>①</cNum> calendar 
          </choice>
          <choice ansnum="2">
            <cNum>②</cNum> impression 
          </choice>
          <choice ansnum="3">
            <cNum>③</cNum> operate 
          </choice>
          <choice ansnum="4">
            <cNum>④</cNum> popular 
          </choice>
          <br/>
        </choices>
      </question>
      <question anscol="A5" answer_style="multipleChoice" answer_type="orthography" id="Q8" knowledge_type="PRN" minimal="yes">
        <label>問２</label>
        <data id="D4" type="text">
           transportation <ansColumn id="A5">5</ansColumn>
          <br/>
        </data>
        <choices anscol="A5" comment="">
          <choice ansnum="1">
            <cNum>①</cNum> authority 
          </choice>
          <choice ansnum="2">
            <cNum>②</cNum> experiment 
          </choice>
          <choice ansnum="3">
            <cNum>③</cNum> fundamental 
          </choice>
          <choice ansnum="4">
            <cNum>④</cNum> melancholy 
          </choice>
          <br/>
        </choices>
      </question>
    </question>
    <question anscol="A6" answer_style="multipleChoice" answer_type="sentence" id="Q53" knowledge_type="FOC_2" minimal="yes">
      <label>Ｃ</label>
      <instruction>
         次の文において，話者が太字で示した語を特に強調して発音した場合，話者が伝えようとした意図はどれが最も適当か。以下の①～④のうちから一つ選べ。<br/>
      </instruction>
      <ansColumn id="A6">6</ansColumn>
      <br/>
      <br/>
      <data id="D36" type="text">
        Max's mother told him to do his <uText id="U13">math</uText> homework immediately.<br/>
      </data>
      <br/>
      <choices anscol="A6">
        <choice ansnum="1">
          <cNum>①</cNum> It is this subject that should be done now. 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> It was not his father who urged Max to study. 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> Max tends to leave things until the last moment. 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> Max will not do anything without instructions. 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A7" answer_style="multipleChoice" answer_type="sentence" id="Q54" knowledge_type="FOC_1" minimal="yes">
      <label>Ｄ</label>
      <instruction>
        次の下線を引いた文において，強く発音する部分を最も適当に示しているのはどれか。以下の①～④のうちから一つ選べ。強く発音する部分は●で示してある。
      </instruction>
      <ansColumn id="A7">7</ansColumn>
      <br/>
      <data id="D37" type="text">
        <br/>
         While holding down button C, press both D and F for five seconds. Oh, dear.<uText id="U14"> It's so complicated that I feel confused just reading the manual</uText>.<br/>
        <br/>
      </data>
      <choices anscol="A7">
        <choice ansnum="1">
          <cNum>①</cNum> It's so complicated that I feel confused just reading the manual. 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> It's so complicated that I feel confused just reading the manual. 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> It's so complicated that I feel confused just reading the manual. 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> It's so complicated that I feel confused just reading the manual. 
        </choice>
        <br/>
      </choices>
    </question>
  </question>
</exam>

=== TodaiRobotProject/classB/sample_problems/sample-Rinri.xml
<?xml version='1.0'?>
<!DOCTYPE exam PUBLIC "-//TOROBO//TOROBO ANNOTATION 1.0//EN" "torobo.dtd">
<?xml-stylesheet type="text/css" href="../torobo.css"?>
<exam source="National Center For University Entrance Examination" subject="Rinri(main exam)" year="2009">
  Center-2009--Main-Rinri<br/>
  <title>
    2009年度 本試験 倫理<br/>
    <br/>
  </title>
  <question id="Q1" minimal="no">
    <label>【１】</label>
    <instruction>
      <br/>
      <br/>
       次の文章を読み，以下の問い(問１～３)に答えよ。<br/>
    </instruction>
    (配点 ８)
    <data id="D0" type="text">
      <br/>
       青年期は，自我に目覚め，生きる意味を巡って悩み始める時期であると言われる。しかし，果たして，<uText id="U1"><label>(a)</label>悩んでいるのは青年だけなのだろうか</uText>。<br/>
       例えば，成人期にあたる親世代について考えてみよう。成人期において，人は家庭生活や職業生活のうえで様々な役割の変化を経験し，そこで遭遇する様々な問題への対応を迫られる。そして，これらの問題に対して，時に葛藤を覚え，また時に現在確立している自身の自我同一性(アイデンティティ)の危機を感じることもある。<br/>
       このように，青年期が，「自分自身を見つめ，自己を確立していく」初めての時期だとすれば，<uText id="U2"><label>(b)</label>成人期は，これまでの自分のあり方に危機を感じたときに，いったん確立した自己の問い直し，再確立が求められる時期である</uText>。<br/>
       このように考えると，<uText id="U3"><label>(c)</label>人生は，常に自分と向き合いながら，成長し続ける旅</uText>だと言うこともできる。<br/>
      <br/>
    </data>
    <question anscol="A2" answer_style="multipleChoice" answer_type="sentence" id="Q3" knowledge_type="GK" minimal="yes">
      <label>問２</label>
      <instruction>
         下線部<ref comment="" target="U2">(b)</ref>に関して，自我同一性を見失っている心理状態の例として最も適当なものを，次の①～④のうちから一つ選べ。
      </instruction>
      <ansColumn id="A2">２</ansColumn><br/>
      <choices anscol="A2" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 定年で，仕事を辞め，空虚さを感じていた時もありました。今，これまでの人生を振り返って自分史を書き始めています。思いのほか，たくさんの人にお世話になってきた自分を改めて感じています。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 結婚を前提に特定の人と付き合っている友だちがおり，すごく生活が充実しているようにみえます。結婚を焦る気持ちも正直ありますが，今，仕事が充実しており，しばらく仕事をがんばろうかなと思っています。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 小学生の子どもがいます。学校に行ったり行かなかったりで，友だちとトラブルがあったのではないかと心配です。自分の会社での仕事も忙しく，大きな仕事の責任者となっています。いろいろと考えることが多いです。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 子どもも大学に入り，家を出ていきました。心の中にぽっかりと穴が空いた感じが続いています。自分の人生っていったい何だったのだろうか，自分の存在意義って何なのだろうか，いろいろと思い悩んでいます。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A3" answer_style="multipleChoice" answer_type="(symbol-symbol)*4" id="Q4" knowledge_type="KS" minimal="yes">
      <label>問３</label>
      <instruction>
         下線部<ref comment="" target="U3">(c)</ref>に関連して，エリクソンは，人生を八つの発達段階に分けて，それぞれの特徴について記述している。そのうち次の青年期以降の四つの発達段階ア～エとその特徴Ａ～Ｄとの組合せとして最も適当なものを，以下の①～⑥のうちから一つ選べ。
      </instruction>
      <ansColumn id="A3">３</ansColumn><br/>
      <data id="D6" type="table">
        <br/>
        <lText id="L1"><label>ア</label> 青年期 </lText><lText id="L2"><label>イ</label> プレ成人期(成人前期)<br/>
        </lText><lText id="L3"><label>ウ</label> 成人期(成人中期)</lText><lText id="L4"><label>エ</label> 老年期(成人後期)<br/>
        </lText><br/>
        <lText id="L5"><label>Ａ</label> これまで培ってきた自分自身に対する認識を基盤として，特定の人との友情，愛，性的親密さを得ることが求められる。<br/>
        </lText><lText id="L6"><label>Ｂ</label> 自分は何者なのか，何をなすべきなのかという自己についてのゆれを克服し，自己確立についての確信を得ることが求められる。<br/>
        </lText><lText id="L7"><label>Ｃ</label> いろいろなことがあったこれまでの人生のすべてを，自分のものとして，受け入れることが求められる。<br/>
        </lText><lText id="L8"><label>Ｄ</label> 次の世代を支えていく子どもたちを生み，育てていくことに対し，積極的に関与することが求められる。<br/>
        </lText>
      </data>
      <br/>
      <choices anscol="A3" comment="">
        <choice ansnum="1">
          <cNum>①</cNum><ref comment="" target="L1">ア</ref>−<ref comment="" target="L6">Ｂ</ref><ref comment="" target="L2">イ</ref>−<ref comment="" target="L5">Ａ</ref><ref comment="" target="L3">ウ</ref>−<ref comment="" target="L8">Ｄ</ref><ref comment="" target="L4">エ</ref>−<ref comment="" target="L7">Ｃ</ref>
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum><ref comment="" target="L1">ア</ref>−<ref comment="" target="L5">Ａ</ref><ref comment="" target="L2">イ</ref>−<ref comment="" target="L7">Ｃ</ref><ref comment="" target="L3">ウ</ref>−<ref comment="" target="L6">Ｂ</ref><ref comment="" target="L4">エ</ref>−<ref comment="" target="L8">Ｄ</ref>
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum><ref comment="" target="L1">ア</ref>−<ref comment="" target="L5">Ａ</ref><ref comment="" target="L2">イ</ref>−<ref comment="" target="L6">Ｂ</ref><ref comment="" target="L3">ウ</ref>−<ref comment="" target="L8">Ｄ</ref><ref comment="" target="L4">エ</ref>−<ref comment="" target="L7">Ｃ</ref>
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum><ref comment="" target="L1">ア</ref>−<ref comment="" target="L6">Ｂ</ref><ref comment="" target="L2">イ</ref>−<ref comment="" target="L7">Ｃ</ref><ref comment="" target="L3">ウ</ref>−<ref comment="" target="L8">Ｄ</ref><ref comment="" target="L4">エ</ref>−<ref comment="" target="L5">Ａ</ref>
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum><ref comment="" target="L1">ア</ref>−<ref comment="" target="L5">Ａ</ref><ref comment="" target="L2">イ</ref>−<ref comment="" target="L6">Ｂ</ref><ref comment="" target="L3">ウ</ref>−<ref comment="" target="L7">Ｃ</ref><ref comment="" target="L4">エ</ref>−<ref comment="" target="L8">Ｄ</ref>
        </choice>
        <choice ansnum="6">
          <cNum>⑥</cNum><ref comment="" target="L1">ア</ref>−<ref comment="" target="L6">Ｂ</ref><ref comment="" target="L2">イ</ref>−<ref comment="" target="L5">Ａ</ref><ref comment="" target="L3">ウ</ref>−<ref comment="" target="L7">Ｃ</ref><ref comment="" target="L4">エ</ref>−<ref comment="" target="L8">Ｄ</ref>
        </choice>
        <br/>
      </choices>
    </question>
  </question>
</exam>

=== TodaiRobotProject/classB/sample_problems/sample-SeibutsuI.xml
<?xml version='1.0'?>
<!DOCTYPE exam PUBLIC "-//TOROBO//TOROBO ANNOTATION 1.0//EN" "torobo.dtd">
<?xml-stylesheet type="text/css" href="../torobo.css"?>
<exam source="National Center For University Entrance Examination" subject="SeibutsuI(main exam)" year="2009">
  Center-2009--Main-SeibutsuI<br/>
  <title>
    2009年度 本試験 生物Ⅰ<br/>
    <br/>
  </title>
  <question id="Q1" minimal="no">
    <label>【１】</label>
    <instruction>
      <br/>
      <br/>
       多細胞生物の個体の形成に関する次の文章を読み，以下の問い(問１～４)に答えよ。<br/>
    </instruction>
    (配点 20)<br/>
    <data id="D8" type="text">
      多細胞生物の体が形作られる際には，<uText id="U1"><label>ア</label>受精卵から体細胞分裂によって細胞数が増える</uText>ことが必要である。これに加えて，体細胞分裂の方向は，体の形を決めるのに重要なはたらきをもつ。<br/>
       また，<uText id="U2"><label>イ</label>個々の細胞が特定の時期，場所で分化する</uText>ことによって，<uText id="U3"><label>ウ</label>異なる機能をもつ様々な細胞ができる</uText>。こうした細胞は，似たはたらきと形状をもつものが集まって <blank id="B1"><label>エ</label></blank> を形成する。さらに複数の <ref comment="" target="B1">エ</ref> が相互に関連をもってまとまることで，高度な機能をもつ <blank id="B2"><label>オ</label></blank> となる。ほ乳類などの動物では，複数の <ref comment="" target="B2">オ</ref> が集まって一連のはたらきを分担して受けもつ <blank id="B3"><label>カ</label></blank> をつくる。<br/>
    </data>
    <br/>
    <question anscol="A11 A12 A13" answer_style="multipleChoice" answer_type="term_other" id="Q2" knowledge_type="KS" minimal="yes">
      <label>問１</label>
      <instruction>
        <ref comment="" target="B1">エ</ref> ～ <ref comment="" target="B3">カ</ref> に入る語として最も適当なものを，次の①～⑦のうちからそれぞれ一つずつ選べ。<br/>
      </instruction>
      <ref target="B1">エ</ref><ansColumn id="A11">１</ansColumn><ref comment="" target="B2">オ</ref><ansColumn id="A12">２</ansColumn><ref comment="" target="B3">カ</ref><ansColumn id="A13">３</ansColumn><br/>
      <choices anscol="A11 A12 A13" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 細胞系 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 群 体 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 器 官 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 器官系 
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> 組 織 
        </choice>
        <choice ansnum="6">
          <cNum>⑥</cNum> 組織系 
        </choice>
        <choice ansnum="7">
          <cNum>⑦</cNum> 個 体 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A16" answer_style="multipleChoice" answer_type="term_other" id="Q4" knowledge_type="KS" minimal="yes">
      <label>問３</label>
      <instruction>
         下線部<ref comment="" target="U2">イ</ref>に関連して，多細胞生物の発生過程では，一部の細胞が死ぬことによって特定の機能をもつ構造を形成する場合がある。植物において，こうしてつくられる構造として最も適当なものを，次の①～⑤のうちから一つ選べ。
      </instruction>
      <ansColumn id="A16">６</ansColumn><br/>
      <choices anscol="A16" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 根 毛 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 柱 頭 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 師 管 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 道 管 
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> 気 孔 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A17" answer_style="multipleChoice" answer_type="sentence" id="Q5" knowledge_type="KS" minimal="yes">
      <label>問４</label>
      <instruction>
         下線部<ref comment="" target="U3">ウ</ref>に関して，分化した細胞の機能や形態，構造についての記述として最も適当なものを，次の①～⑥のうちから一つ選べ。
      </instruction>
      <ansColumn id="A17">７</ansColumn><br/>
      <choices anscol="A17" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 消化酵素などを分泌する外分泌腺の腺細胞は，ゴルジ体が発達した細胞であり，血管を取り囲むような閉じた袋の内側に並んでいる。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> ヒト内耳の半規管には感覚毛というべん毛をもつ細胞が存在し，このべん毛がおおい膜とこすれることで，基底膜の振動を音として感知する。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 神経の軸索の末端には，興奮を伝達するための神経伝達物質をためたシナプス小胞という特殊な構造体が含まれる。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> ほ乳類の骨細胞は，その細胞質に多量のカルシウムを含み，かつ，細胞同士が密に集まることで骨の機械的な強度を保っている。 
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum> 被子植物の表皮細胞のほとんどは，孔辺細胞にみられるように，光合成を行うための葉緑体をもつ。 
        </choice>
        <choice ansnum="6">
          <cNum>⑥</cNum> 動物の運動を担う筋肉細胞では，筋原繊維に加えて，運動に必要な酸素を盛んに発生するミトコンドリアが発達している。 
        </choice>
        <br/>
      </choices>
    </question>
  </question>
</exam>
