=== TodaiRobotProject/classB/Center/Center-xml-dtd/torobo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD renewed on Jul 30, 2014. 7/22からの変更内容：(1)noteの子要素にsourceを追加。 6/30からの変更内容：(1)rbの子要素にunkを追加。(2)noteの子要素にquoteを追加。(3)captionの子要素にsubとsupを追加。  6/26からの変更内容：(1)cellの子要素にsupおよびsubを追加。(2)noteの子要素にformulaを追加。(3)infoの子要素にformulaを追加。(4)formulaの子要素にuTextを追加。(5)lineStart, paragraph要素を追加。(6)dataの子要素に、lineStart, paragraphを追加。 2014/3/13からの変更内容：(1)pageStartのpn属性をCDATAからIDに変更 (2)pageEndのpn属性をIMPLIEDに変更　3/13からの変更内容：(1)source, noteの子要素にrefを追加 12/20からの変更内容：(1)cellの子要素にimgを追加。(2)examの子要素に、pageStart, pageEndを追加。(3)lTextの子要素に、lTextを追加。(4)supおよびsubの子要素にrefを追加。  9/19からの変更内容：(1)ruby, rb, rtを追加。(2)unkタグを追加。(3)pageStart, pageEndを追加。  9/3からの変更内容：(1)ansColumnの下にblankがこれるようにした。(2)mathが、caption, data, questionの子になれるようにした。 8/21からの変更内容：(1)<okuriL><okuri><sub><sup><kaeri>がchoice, instruction, data, uText, lText, noteの子になれるようにした。(2)<sub><sup><ref>がformulaの子になれるようにした。(3)dataの子にcaptionが二つ入っているのを一つにした。(4)blankがsup, subの子になれるようにした。 8/20からの変更内容：(1) adataの子として、formula, mathを追加。8/19からの変更内容：<okuriL><okuri><sub><sup><kaeri>を追加した。 5/24からの変更内容：(1)imgにcorresponding_obj属性を追加。(2)adata要素を追加。属性として、id、type、fieldを定義。(3)adataが、data, choices, choice, question, instructionの各要素の子になれるようにした。 5/13日からの変更内容：(1)formulaの子にblankを追加 (2)choiceにansnum属性を追加 (3)cellの子にlTextを追加 (4) question, choicesのanscol属性をCDATAに-->

<!ELEMENT paragraph (#PCDATA |garbled| blank | img | lText | tbl | label | uText | caption | ansColumn | source | note | quote | choice|cNum|missing|ref |data|br|choices|formula|row|cell|adata|okuriL|okuri|sub|sup|kaeri|math|pageStart|pageEnd|unk|ruby|lineStart)*>
<!ATTLIST paragraph
	prn ID #REQUIRED
>

<!ELEMENT lineStart EMPTY>
<!ATTLIST lineStart
	ln ID #REQUIRED
>

<!ELEMENT pageStart EMPTY>
<!ATTLIST pageStart
	pn ID #REQUIRED
>
<!ELEMENT pageEnd EMPTY>
<!ATTLIST pageEnd
	pn CDATA #IMPLIED
>

<!ELEMENT unk (#PCDATA)*>
<!ATTLIST unk
	imgsrc CDATA #IMPLIED
	comment CDATA #IMPLIED
>

<!ELEMENT ruby (#PCDATA|rb|rt)*>
<!ELEMENT rb (#PCDATA|kaeri|unk)*>
<!ELEMENT rt (#PCDATA)*>

<!ELEMENT okuriL (#PCDATA)*>
<!ELEMENT sup (#PCDATA|blank|ref)*>
<!ELEMENT sub (#PCDATA|blank|ref)*>
<!ELEMENT kaeri (#PCDATA)*>
<!ELEMENT okuri (#PCDATA)*>

<!ELEMENT adata (#PCDATA|choices|choice|tbl|formula|math)*>
<!ATTLIST adata
	id ID #REQUIRED
	type CDATA #IMPLIED
	field CDATA #IMPLIED
>
<!ELEMENT caption (#PCDATA | label|garbled|ref|missing|blank|br|choice|cNum|lText|formula|quote|source|uText|math|pageStart|pageEnd|unk|ruby|sub|sup)*>
<!ELEMENT uText (#PCDATA | label|garbled|ref|missing|blank|br|choice|cNum|lText|formula|quote|source|uText|math|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST uText
	id ID #REQUIRED
>
<!ELEMENT title (#PCDATA|garbled |missing|br)*>
<!ELEMENT tbl (#PCDATA|row|label|choice|cNum|br|cell|blank|ref|uText|choices|formula|quote|source|garbled|missing|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST tbl
	numOfCols CDATA #IMPLIED
	numOfRows CDATA #IMPLIED
>
<!ELEMENT row (#PCDATA | cell|label|choice|br|blank|ref|cNum|uText|choices|formula|quote|source|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT ref (#PCDATA|garbled |missing|br|formula|uText|lText|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST ref
	comment CDATA #IMPLIED
	target IDREF #IMPLIED
>
<!ELEMENT question (#PCDATA |garbled| label | instruction | data | question | ansColumn | choice | img | tbl | choices|cNum|missing |ref|br|formula|quote|source|lText|info|adata|math|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST question
	id ID #REQUIRED
	minimal (null|yes | no) #REQUIRED
	answer_style CDATA #IMPLIED
	answer_type CDATA #IMPLIED
	knowledge_type CDATA #IMPLIED
	anscol CDATA #IMPLIED
	title CDATA #IMPLIED
	sectionId CDATA #IMPLIED
	comment CDATA #IMPLIED
>
<!ELEMENT label (#PCDATA|br|garbled|missing)*>
<!ELEMENT lText (#PCDATA |garbled| label|ref|missing|blank|br|choice|cNum|uText|formula|quote|source|math|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby|lText)*>
<!ATTLIST lText
	id ID #REQUIRED
>
<!ELEMENT instruction (#PCDATA |garbled| ref|missing |label |ansColumn|lText|uText|br|blank|formula|quote|source|img|choices|data|math|adata|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT info (#PCDATA|garbled|missing|br|formula)*>
<!ELEMENT img EMPTY>
<!ATTLIST img
	src CDATA #REQUIRED
	comment CDATA #IMPLIED
	corresponding_obj IDREFS #IMPLIED
>
<!ELEMENT exam (#PCDATA|title|info|question|cNum|label|garbled|missing|choice|choices|br|ref|ansColumn|pageStart|pageEnd)*>
<!ATTLIST exam
	source CDATA #IMPLIED
	srcTxtURL CDATA #IMPLIED
	subject CDATA #REQUIRED
	year CDATA #IMPLIED
	range_of_options IDREFS #IMPLIED
	num_of_options CDATA #IMPLIED
	xml:space (default|preserve) "default"
>
<!ELEMENT data (#PCDATA |garbled| blank | img | lText | tbl | label | uText | caption | ansColumn | source | note | quote | choice|cNum|missing|ref |data|br|choices|formula|row|cell|adata|okuriL|okuri|sub|sup|kaeri|math|pageStart|pageEnd|unk|ruby|lineStart|paragraph)*>
<!ATTLIST data
	id ID #REQUIRED
	type (complex | text | table | image ) #REQUIRED
>
<!ELEMENT choices (#PCDATA |garbled| cNum | ref | img | tbl | row | cell| uText | lText |choice|missing|br |label|formula|quote|source|adata|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST choices
	comment CDATA #IMPLIED
	anscol CDATA #IMPLIED
>
<!ELEMENT choice (#PCDATA |garbled| cNum | ref | img | tbl | uText | lText|missing |cell|br|label|formula|quote|source|math|data|adata|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby)*>
<!ATTLIST choice
	ra (no | yes) #IMPLIED
	comment CDATA #IMPLIED
	ansnum CDATA #IMPLIED
>
<!ELEMENT cell (#PCDATA |garbled| blank | ansColumn | ref|missing|label|cNum|br |choice|uText|choices|formula|quote|source|lText|math|pageStart|pageEnd|unk|ruby|img|sub|sup)*>
<!ATTLIST cell
	type (label | data) #IMPLIED
	colspan CDATA #IMPLIED
	rowspan CDATA #IMPLIED
>

<!ELEMENT cNum (#PCDATA|garbled|missing|br)*>
<!ELEMENT blank (#PCDATA |garbled| label | ansColumn|missing|br)*>
<!ATTLIST blank
	id ID #REQUIRED
	digits CDATA #IMPLIED
>
<!ELEMENT ansColumn (#PCDATA | label|garbled|missing|ref|br|blank)*>
<!ATTLIST ansColumn
	id ID #REQUIRED
>
<!ELEMENT source (#PCDATA|garbled|missing|br|pageStart|pageEnd|unk|ruby|ref)*>
<!ELEMENT note (#PCDATA | label|garbled|missing|br|okuriL|okuri|sub|sup|kaeri|pageStart|pageEnd|unk|ruby|ref|formula|quote|source)*>
<!ATTLIST note id ID #REQUIRED>
<!ELEMENT quote (#PCDATA|garbled|missing|br|uText|lText|ref|label|blank|note|source|pageStart|pageEnd|unk|ruby)*>
<!ELEMENT garbled (#PCDATA|br|label)*>
<!ATTLIST garbled correction CDATA #IMPLIED>
<!ELEMENT missing EMPTY>
<!ATTLIST missing string CDATA #IMPLIED>
<!ELEMENT formula (#PCDATA|garbled|missing|br|blank|ref|sub|sup|uText)*>
<!ATTLIST formula comment CDATA #IMPLIED>
<!ELEMENT br EMPTY>

=== TodaiRobotProject/classB/sample_problems/sample-Seijikeizai.xml
<?xml version='1.0'?>
<!DOCTYPE exam PUBLIC "-//TOROBO//TOROBO ANNOTATION 1.0//EN" "torobo.dtd">
<?xml-stylesheet type="text/css" href="../torobo.css"?>
<exam source="National Center For University Entrance Examination" subject="Seijikeizai(main exam)" year="2009">Center-2009--Main-Seijikeizai<br/>
  <title>2009年度 本試験 政治・経済<br/>
    <br/>
  </title>
  <question id="Q12" minimal="no">
    <label>【２】</label>
    <instruction>
      <br/>
      <br/> 次の文章を読み，以下の問い(問１～７)に答えよ。<br/>
    </instruction>(配点 19)<data id="D1" type="text">
      <br/> 日本国憲法が保障する<uText id="U11">
        <label>(a)</label>表現の自由</uText>は，自由なコミュニケーションを通じて個人の人格を発展させ，また多様な意見の表明を通じて<uText id="U12">
        <label>(b)</label>民主政治</uText>を機能させる重要な人権である。<br/> 表現の自由によって保障される表現の形態は，今日の情報技術の進展に伴い，いっそう多様化した。とりわけ，<uText id="U13">
        <label>(c)</label>インターネット</uText>の登場は，いつでも，どこでも，だれでも，無数の情報を瞬時にかつグローバルに発信したり，受信したりすることを可能にした。<br/> しかし，インターネット上の表現の中には，電子匿名掲示板における一部の書き込みにみられるように，他人の<uText id="U14">
        <label>(d)</label>プライバシー</uText>や名誉を侵害するものや，他人に対する危害を予告し不安を煽りたてるものもある。さらに，音楽や映像などのやりとりをめぐっては，著作権の侵害も問題となっている。<br/> これらの侵害が匿名で行われた場合，一般に，<uText id="U15">
        <label>(e)</label>裁判</uText>による救済は困難となる。そこで，<uText id="U16">
        <label>(f)</label>国会</uText>は，発信者情報の開示請求を認める<uText id="U17">
        <label>(g)</label>法律を制定</uText>するなどの対応をしてきた。しかし，被害者救済の実効性という点で，まだ課題が残されている。<br/> いま，インターネットを通じた表現の自由と，その表現によって被害を受ける者の権利との，双方に配慮した解決策が求められている。<br/>
      <br/>
    </data>
    <question anscol="A11" answer_style="multipleChoice" answer_type="sentence" id="Q13" knowledge_type="KS" minimal="yes">
      <label>問１</label>
      <instruction> 下線部<ref comment="" target="U11">(a)</ref>に関連する記述として最も適当なものを，次の①～④のうちから一つ選べ。 </instruction>
      <ansColumn id="A11">11</ansColumn>
      <br/>
      <choices anscol="A11" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 表現の自由には，楽曲を演奏する自由は含まれない。 </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 表現の自由には，報道機関の報道の自由も含まれる。 </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 検閲の禁止は，一度刊行した出版物の再発行を禁じるものである。 </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 通信の秘密は，電信・電話による通信の内容を対象としていない。 </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A12" answer_style="multipleChoice" answer_type="sentence" id="Q14" knowledge_type="KS" minimal="yes">
      <label>問２</label>
      <instruction> 下線部<ref comment="" target="U12">(b)</ref>に関連する日本の制度についての記述として最も適当なものを，次の①～④のうちから一つ選べ。 </instruction>
      <ansColumn id="A12">12</ansColumn>
      <br/>
      <choices anscol="A12" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 憲法改正のためには，国会の発議した憲法改正案が，国民投票の３分の２以上の賛成で承認されなければならない。 </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 国民には，衆参両院の議員，地方自治体の長と議会の議員を，秘密投票で選出することが保障されている。 </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 国民には，最高裁判所の裁判官を，その任命後初めて行われる衆議院議員総選挙または参議院議員通常選挙の際に，審査することが保障されている。 </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 内閣総理大臣を国民が直接選出できるようにするには，憲法の改正は不要だが，法律で定めなければならない。 </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A13" answer_style="multipleChoice" answer_type="sentence" id="Q15" knowledge_type="KS" minimal="yes">
      <label>問３</label>
      <instruction> 下線部<ref comment="" target="U13">(c)</ref>に関連する記述として最も適当なものを，次の①～④のうちから一つ選べ。 </instruction>
      <ansColumn id="A13">13</ansColumn>
      <br/>
      <choices anscol="A13" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> ユビキタス・ネットワーク社会とは，インターネットを利用して得られる情報量の格差が生じた社会をいう。 </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 電子政府構想(e-Japan構想)は，IT(情報技術)を利用することにより，外国政府との折衝の迅速化を図ることを目的として登場した。 </choice>
        <choice ansnum="3">
          <cNum>③</cNum> コーポレート・ガバナンスは，企業内のコンピュータに対する外部からの不正アクセスを防止するために導入されている。 </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 電子商取引(eコマース)には，携帯電話を利用してインターネットに接続する個人が，業者から商品を購入することも含まれる。 </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A14" answer_style="multipleChoice" answer_type="(symbol-symbol)*3" id="Q16" knowledge_type="KS" minimal="yes">
      <label>問４</label>
      <instruction> 下線部<ref comment="" target="U14">(d)</ref>の権利は，新しい人権として主張されているものの一つである。新しい人権<ref target="L7">Ａ</ref>～<ref target="L9">Ｃ</ref>と，その内容<ref target="L10">ア</ref>～<ref target="L12">ウ</ref>との組合せとして正しいものを，以下の①～⑥のうちから一つ選べ。 </instruction>
      <ansColumn id="A14">14</ansColumn>
      <br/>
      <br/>
      <data id="D6" type="text">
        <lText id="L7">
          <label>Ａ</label> アクセス権</lText>
        <lText id="L8">
          <label>Ｂ</label> 知る権利<br/>
        </lText>
        <lText id="L9">
          <label>Ｃ</label> プライバシー権<br/>
        </lText>
        <br/>
        <lText id="L10">
          <label>ア</label> 自分に関する情報を自らコントロールする権利<br/>
        </lText>
        <lText id="L11">
          <label>イ</label> マスメディアを利用して意見を発表したり反論したりする権利<br/>
        </lText>
        <lText id="L12">
          <label>ウ</label> 政府情報の開示を求める権利<br/>
        </lText>
        <br/>
      </data>
      <choices anscol="A14" comment="">
        <choice ansnum="1">
          <cNum>①</cNum>
          <ref comment="" target="L7">Ａ</ref>−<ref comment="" target="L10">ア</ref>
          <ref comment="" target="L8">Ｂ</ref>−<ref comment="" target="L11">イ</ref>
          <ref comment="" target="L9">Ｃ</ref>−<ref comment="" target="L12">ウ</ref>
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum>
          <ref comment="" target="L7">Ａ</ref>−<ref comment="" target="L10">ア</ref>
          <ref comment="" target="L8">Ｂ</ref>−<ref comment="" target="L12">ウ</ref>
          <ref comment="" target="L9">Ｃ</ref>−<ref comment="" target="L11">イ</ref>
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum>
          <ref comment="" target="L7">Ａ</ref>−<ref comment="" target="L11">イ</ref>
          <ref comment="" target="L8">Ｂ</ref>−<ref comment="" target="L10">ア</ref>
          <ref comment="" target="L9">Ｃ</ref>−<ref comment="" target="L12">ウ</ref>
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum>
          <ref comment="" target="L7">Ａ</ref>−<ref comment="" target="L11">イ</ref>
          <ref comment="" target="L8">Ｂ</ref>−<ref comment="" target="L12">ウ</ref>
          <ref comment="" target="L9">Ｃ</ref>−<ref comment="" target="L10">ア</ref>
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum>
          <ref comment="" target="L7">Ａ</ref>−<ref comment="" target="L12">ウ</ref>
          <ref comment="" target="L8">Ｂ</ref>−<ref comment="" target="L10">ア</ref>
          <ref comment="" target="L9">Ｃ</ref>−<ref comment="" target="L11">イ</ref>
        </choice>
        <choice ansnum="6">
          <cNum>⑥</cNum>
          <ref comment="" target="L7">Ａ</ref>−<ref comment="" target="L12">ウ</ref>
          <ref comment="" target="L8">Ｂ</ref>−<ref comment="" target="L11">イ</ref>
          <ref comment="" target="L9">Ｃ</ref>−<ref comment="" target="L10">ア</ref>
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A15" answer_style="multipleChoice" answer_type="sentence" id="Q17" knowledge_type="KS" minimal="yes">
      <label>問５</label>
      <instruction> 下線部<ref comment="" target="U15">(e)</ref>に関連して，日本における裁判の制度や歴史についての記述として最も適当なものを，次の①～④のうちから一つ選べ。 </instruction>
      <ansColumn id="A15">15</ansColumn>
      <br/>
      <choices anscol="A15" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 日本国憲法では，刑事被告人に弁護人依頼権が認められている。 </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 陪審制はこれまで実施されたことはない。 </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 死刑判決を受けた人が再審で無罪とされた例はない。 </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 日本国憲法では，国を被告とする裁判が禁止されている。 </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A16" answer_style="multipleChoice" answer_type="sentence" id="Q18" knowledge_type="KS" minimal="yes">
      <label>問６</label>
      <instruction> 下線部<ref comment="" target="U16">(f)</ref>の議員に認められている日本国憲法上の地位についての記述として誤っているものを，次の①～④のうちから一つ選べ。 </instruction>
      <ansColumn id="A16">16</ansColumn>
      <br/>
      <choices anscol="A16" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 法律の定める場合を除いて，国会の会期中逮捕されない。 </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 議院内で行った演説について，議院外で責任を問われない。 </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 法律の定めるところにより，国庫から相当額の歳費を受ける。 </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 議員を除名するには，弾劾裁判所の裁判が必要となる。 </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A17" answer_style="multipleChoice" answer_type="sentence" id="Q19" knowledge_type="KS" minimal="yes">
      <label>問７</label>
      <instruction> 下線部<ref comment="" target="U17">(g)</ref>に関連して，日本国憲法上定められている手続についての記述として正しいものを，次の①～④のうちから一つ選べ。 </instruction>
      <ansColumn id="A17">17</ansColumn>
      <br/>
      <choices anscol="A17" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 国務大臣が国会議員でない場合には，法律案について発言するためであっても，衆参両院に出席することができない。 </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 国務大臣が衆議院議員である場合には，法律案について発言するためであっても，参議院に出席することができない。 </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 衆議院で可決され参議院で否決された法律案は，衆議院で出席議員の３分の２以上の多数で再び可決されたときは，法律となる。 </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 衆議院で可決され参議院で60日以内に議決されない法律案は，衆議院の議決が国会の議決とみなされ，そのまま法律となる。 </choice>
        <br/>
      </choices>
    </question>
  </question>
</exam>

=== TodaiRobotProject/classB/sample_problems/sample-Gendaishakai.xml
<?xml version='1.0'?>
<!DOCTYPE exam PUBLIC "-//TOROBO//TOROBO ANNOTATION 1.0//EN" "torobo.dtd">
<?xml-stylesheet type="text/css" href="../torobo.css"?>

<exam source="National Center For University Entrance Examination" subject="Gendaishakai(main exam)" year="2009">
  Center-2009--Main-Gendaishakai<br/>
  <title>
    2009年度 本試験 現代社会<br/><br/>
  </title>
  <question id="Q1" minimal="no">
    <label>【１】</label>
    <instruction>
      <br/><br/> 高校生(Ａ)とその母親(Ｂ)による次の会話文を読み，以下の問い(問１～５)に答えよ。<br/>
    </instruction>
    (配点 14)
    <data id="D0" type="text">
      <br/> Ａ： いよいよ<uText id="U1"><label>(a)</label>裁判員制度</uText>が始まるね。お母さんも裁判に参加できるかもしれないんだよ。すごいことだよね。<br/> Ｂ： 気楽に言わないでよ。そもそもなぜ裁判員制度が導入されたか，知ってる？<br/> Ａ： これまでの裁判が分かりにくくて，国民にとって身近なものじゃなかったから，それを改めるためだよね。国民の司法参加だよ。<br/> Ｂ： 確かに，最近では社会をより良くするための市民参加の必要性が説かれているし，裁判員制度もその一つと言えるのかな。でも，私たちが<uText id="U2"><label>(b)</label>裁判にかかわる機会</uText>は裁判員制度以外にもあるよね。<uText id="U3"><label>(c)</label>日本の司法制度が抱える問題</uText>も裁判の分かりにくさだけではないし，裁判員制度でそれがすべて解決するわけじゃないでしょ。例えば冤罪の問題はどう？<br/> Ａ： うーん。それもそうだけど，プロの裁判官だって間違った判断を絶対にしないとも限らないよ。市民感覚を取り入れることで，より妥当な結論に近づくこともあると思う。<br/> Ｂ： そう考えるとますます裁判員になるのは気が重いな。裁判は，時には判決によって人の生命を奪うことも認めるものだし，思い込みや世論に流されてしまうと逆に<uText id="U4"><label>(d)</label>人権</uText>の重大な侵害を引き起こしかねないでしょう。<br/> Ａ： 一人一人の人権感覚が問われることにもなるね。<uText id="U5"><label>(e)</label>司法を民主化することも，「人権の砦」としての役割をちゃんと果たせるようにすることも，どちらも重要で，確かに難しい問題だなあ</uText>。じっくり考えてみるよ。<br/><br/>
    </data>
    <question anscol="A1" answer_style="multipleChoice" answer_type="(symbol-sentence)*3" id="Q2" knowledge_type="KS" minimal="yes">
      <label>問１</label>
      <instruction>
         下線部<ref comment="" target="U1">(a)</ref>の概要を記述した次の文章中の <label>ア</label> ～ <label>ウ</label> に入る語句の組合せとして最も適当なものを，以下の①～⑧のうちから一つ選べ。
      </instruction>
      <ansColumn id="A1">１</ansColumn><br/>
      <data id="D6" type="text">
        <br/> 日本の裁判員制度とは，国政選挙の有権者から <blank id="B1"><label>ア</label></blank> 選ばれた裁判員が <blank id="B2"><label>イ</label></blank> について，裁判官と共に事実を認定し，評決をする制度である。裁判員に選ばれた者は正当な理由がない限り辞退することはできないが，学生などには一般に辞退が認められている。裁判員には審理への出頭義務や <blank id="B3"><label>ウ</label></blank> が課せられ，これらの義務違反に対しては罰則も設けられている。<br/>
      </data>
      <br/>
      <choices anscol="A1" comment="">
        <choice ansnum="1">
          <cNum>①</cNum><ref comment="" target="B1">ア</ref> 選挙によって <ref comment="" target="B2">イ</ref> すべての刑事事件 <ref comment="" target="B3">ウ</ref> 氏名の公表義務<br/>
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum><ref comment="" target="B1">ア</ref> 選挙によって <ref comment="" target="B2">イ</ref> すべての刑事事件 <ref comment="" target="B3">ウ</ref> 守秘義務<br/>
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum><ref comment="" target="B1">ア</ref> 選挙によって <ref comment="" target="B2">イ</ref> 特定の刑事事件 <ref comment="" target="B3">ウ</ref> 氏名の公表義務<br/>
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum><ref comment="" target="B1">ア</ref> 選挙によって <ref comment="" target="B2">イ</ref> 特定の刑事事件 <ref comment="" target="B3">ウ</ref> 守秘義務<br/>
        </choice>
        <choice ansnum="5">
          <cNum>⑤</cNum><ref comment="" target="B1">ア</ref> 無作為に <ref comment="" target="B2">イ</ref> すべての刑事事件 <ref comment="" target="B3">ウ</ref> 氏名の公表義務<br/>
        </choice>
        <choice ansnum="6">
          <cNum>⑥</cNum><ref comment="" target="B1">ア</ref> 無作為に <ref comment="" target="B2">イ</ref> すべての刑事事件 <ref comment="" target="B3">ウ</ref> 守秘義務<br/>
        </choice>
        <choice ansnum="7">
          <cNum>⑦</cNum><ref comment="" target="B1">ア</ref> 無作為に <ref comment="" target="B2">イ</ref> 特定の刑事事件 <ref comment="" target="B3">ウ</ref> 氏名の公表義務<br/>
        </choice>
        <choice ansnum="8">
          <cNum>⑧</cNum><ref comment="" target="B1">ア</ref> 無作為に <ref comment="" target="B2">イ</ref> 特定の刑事事件 <ref comment="" target="B3">ウ</ref> 守秘義務<br/>
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A2" answer_style="multipleChoice" answer_type="sentence" id="Q3" knowledge_type="KS" minimal="yes">
      <label>問２</label>
      <instruction>
         下線部<ref comment="" target="U2">(b)</ref>に関して，日本の状況の説明として適当でないものを，次の①～④のうちから一つ選べ。
      </instruction>
      <ansColumn id="A2">２</ansColumn><br/>
      <choices anscol="A2" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 検察審査会は，抽選によって選ばれた国民によって構成され，検察官の不起訴処分の是非について審査する。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 裁判の傍聴は国民の権利であるが，プライバシーの権利を保障するため，刑事事件については，法廷でメモを取ることは許されていない。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 最高裁判所の裁判官に対する国民審査が憲法上認められているが，この制度により罷免された裁判官はいない。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 犯罪被害者の権利・利益を保護するため，刑事事件において被害者が直接被告人に質問することを認める制度が導入されている。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A3" answer_style="multipleChoice" answer_type="sentence" id="Q4" knowledge_type="KS" minimal="yes">
      <label>問３</label>
      <instruction>
         下線部<ref comment="" target="U3">(c)</ref>やそれへの対策に関する記述として適当でないものを，次の①～④のうちから一つ選べ。
      </instruction>
      <ansColumn id="A3">３</ansColumn><br/>
      <choices anscol="A3" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 裁判官の独立を保障するため，最高裁判所が下級裁判所の裁判官の任命に関与することは法的に禁止されている。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 国民の司法へのアクセスを促進するために，法曹人口を増やすなどの司法制度改革が進められている。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 冤罪に問われた人を救済するため，無罪とすべき明らかな証拠が新たに発見された場合などに，再審を請求することを認める制度が設けられている。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 裁判に時間がかかり過ぎるとの指摘がなされており，裁判の迅速化を進めるための法律を制定するなどの改革が行われている。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A4" answer_style="multipleChoice" answer_type="sentence" id="Q5" knowledge_type="KS" minimal="yes">
      <label>問４</label>
      <instruction>
         下線部<ref comment="" target="U4">(d)</ref>に関して，日本の状況の説明として最も適当なものを，次の①～④のうちから一つ選べ。
      </instruction>
      <ansColumn id="A4">４</ansColumn><br/>
      <choices anscol="A4" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 憲法には生存権が明記されており，最高裁判所は，これを直接の根拠として，国民は国に社会保障給付を請求することができるとした。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 名誉を毀損する行為の禁止が，表現の自由に対する制約として認められるように，人権であっても，他者を害する場合等には制約されることがある。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 最高裁判所は，裁判所による雑誌の発売前の差止めが，憲法で明示的に禁止されている検閲に該当すると判断した。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 在外投票は外国に居住している国民の選挙権を保障するための手段であるが，日本の国政選挙で実施されたことはなく，制度導入が求められている。 
        </choice>
        <br/>
      </choices>
    </question>
    <question anscol="A5" answer_style="multipleChoice" answer_type="sentence" id="Q6" knowledge_type="KS" minimal="yes">
      <label>問５</label>
      <instruction>
         下線部<ref comment="" target="U5">(e)</ref>に関連して，民主主義と司法権に関する記述として最も適当なものを，次の①～④のうちから一つ選べ。
      </instruction>
      <ansColumn id="A5">５</ansColumn><br/>
      <choices anscol="A5" comment="">
        <choice ansnum="1">
          <cNum>①</cNum> 日本国憲法は違憲審査の制度を設けており，最高裁判所だけでなくすべての下級裁判所が違憲審査権を行使することができる。 
        </choice>
        <choice ansnum="2">
          <cNum>②</cNum> 日本国憲法は国民主権を採っているため，国会の制定する法律に基づく政治が行われていれば，「法の支配」に一切反しないとされる。 
        </choice>
        <choice ansnum="3">
          <cNum>③</cNum> 大日本帝国憲法は天皇主権をすべてに優越する基本原理としていたが，同時に，裁判所が法律に対して違憲審査権を行使することも認めていた。 
        </choice>
        <choice ansnum="4">
          <cNum>④</cNum> 大日本帝国憲法は「臣民の権利」を保障しており，帝国議会が法律によってこれを制限することは一切できないとされていた。 
        </choice>
        <br/>
      </choices>
    </question>
  </question>
</exam>
